### ISSUE TITLE
HA add-on install fails  -The command '/bin/ash -o pipefail -c wget "https://github.com/tidbyt/pixlet/releases/download/v${PIXLET_VERSION}/pixlet_${PIXLET_VERSION}_linux_${BUILD_ARCH}.tar.gz"' returned a non-zero code: 1

### ISSUE THREAD

**Issue by jonpaterson** [savdagod/ha-addons#1]
after adding the repo and attempting to install the add-on, the following is returned in HA

"The command '/bin/ash -o pipefail -c wget "https://github.com/tidbyt/pixlet/releases/download/v${PIXLET_VERSION}/pixlet_${PIXLET_VERSION}_linux_${BUILD_ARCH}.tar.gz"' returned a non-zero code: 1"

**Comment by savdagod** [comment]
Use the latest version of the addon. I’m assuming you’re installing from a raspberry pi and there were issues with that ${BUILD_ARCH} variable. Should be fixed now.

**Comment by jonpaterson** [comment]
This fixed it.  The host was HA green.  Working well!
