### ISSUE TITLE
FR: Add German translations for new .star files

### ISSUE THREAD

**Issue by savdagod** [savdagod/ha-addons#16]
@IngmarStein can you add German translations to the two new built in files (trashbinsout and trashrecbinsout)?

**Comment by IngmarStein** [comment]
Sure thing.

It reminds me to ask something: should each built-in app be in a separate directory (like the community repo). Apps can consist of multiple Starlark files and the add-on needs to jump through some hoops to really render just a single file. `pixlet render` doesn't work when we put all files in a single directory:

```
❯ pixlet render trashbinsout.star
Error: failed to load applet: reading coffee.star: file does not exist
```

If we change this, one could even clone the community repo to a known location and run most of the apps (those without secrets).

**Comment by savdagod** [comment]
Yes I encountered that error as well. A repo would be a clean way of representing each app. Maybe changing the display folder to something like this in its own repo (TidbytAssistant-community or something):

```
|-apps
|    |-trash
|    |-coffee
|    |-etc…

```

**Comment by IngmarStein** [comment]
Before moving the display folder to a separate repo, let me add support for a directory structure. I think that should be done both for the built-in apps as well as custom ones in the `/homeassistant/tidbyt` directory. We should be able to do that in a backwards-compatible way by checking whether `${content}.star` exists - if not, we attempt to render the app in the `${content}` directory.
