### ISSUE TITLE
Failed Add-On Install: `The command '/bin/ash -o pipefail -c tar -xzf v${PIXLET_VERSION}.tar.gz -C $REPO' returned a non-zero code: 1`

### ISSUE THREAD

**Issue by zenibako** [savdagod/ha-addons#2]
## Hardware
Raspberry Pi 4 (rpi4-64)

## Home Assistant Version
Core 2024.9.2
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

**Comment by savdagod** [comment]
That shouldn't be an error anymore as the add-on now builds pixlet from source. Be sure to check for updates in the add-on store then try to install/rebuild it again.
