### ISSUE TITLE
v1.0.9 Not pushing to Tidbyt

### ISSUE THREAD

**Issue by itsdoublearon** [savdagod/ha-addons#7]
Upgraded to v1.0.9 and the publishing is not working anymore.

s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[webhook] 2024/10/13 02:51:04 caught terminated signal; exiting
2024/10/13 02:51:12 INFO Starting TidbytAssistant server
2024/10/13 02:54:29 INFO Starting TidbytAssistant server
2024/10/13 02:55:56 INFO Starting TidbytAssistant server
2024/10/13 02:57:34 INFO Starting TidbytAssistant server

I'm running HA OS on Proxmox if that helps.

**Comment by savdagod** [comment]
Did you update the integration as well? There are some changes there that are needed for everything to work as normal.

**Comment by itsdoublearon** [comment]
There we go, that was the one step I missed. Functioning again, thanks.
